apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-7ghmcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-7ghmcd
  namespace: my-nginx-7ghmcd
  labels:
    name: nginx-7ghmcd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-7ghmcd
  template:
    metadata:
      namespace: my-nginx-7ghmcd
      labels:
        name: nginx-7ghmcd
    spec:
      containers:
      - name: nginx-7ghmcd
        image: nginx
        ports:
        - containerPort: 80

